services:
  web:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/var/www/html
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:80}:80"

  php-fpm:
    image: "ghcr.io/opdavies/docker-symfony-example-php-fpm:${DOCKER_TAG:-latest}"
    build:
      context: .
    volumes:
      - .:/var/www/html
    environment:
      - "APP_DEBUG=${APP_DEBUG:-0}"
      - "APP_ENV=${APP_ENV:-prod}"
